[package]
name = "cats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"

[lib]
name = "cats"
path = "cats.rs"
crate-type=["dylib"]